version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: protone
      POSTGRES_USER: protone
      POSTGRES_PASSWORD: protone
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - network

networks:
  network:
    driver: bridge

volumes:
  data:
